export const BACKEND_URL = 'http://localhost:8000/timtoolApi/'
export const TOKEN = 'get-token/'
export const TUNE = 'tune/'
export const TUNES = 'tunes/'
export const FAVORIS = 'favoris/'
export const SWITCH_FAVORI = 'switch-favori/'