export const SWITCH_VISIBLE_SIDE_BAR_ON = 'SWITCH_VISIBLE_SIDE_BAR_ON'
export const SWITCH_VISIBLE_SIDE_BAR_OFF = 'SWITCH_VISIBLE_SIDE_BAR_OFF'

export const REINIT_BREADCRUMB = 'REINIT_BREADCRUMB'
export const ADD_TO_BREADCRUMB = 'ADD_TO_BREADCRUMB'
export const ROLL_BACK_NAV_BAR = 'ROLL_BACK_NAV_BAR'

export const SHOW_ALL = 'SHOW_ALL'

