export const SWITCH_VISIBLE_SIDE_BAR_ON = 'SWITCH_VISIBLE_SIDE_BAR_ON'
export const SWITCH_VISIBLE_SIDE_BAR_OFF = 'SWITCH_VISIBLE_SIDE_BAR_OFF'

export const REINIT_BREADCRUMB = 'REINIT_BREADCRUMB'
export const ADD_TO_BREADCRUMB = 'ADD_TO_BREADCRUMB'
export const ROLL_BACK_BREADCRUMB = 'ROLL_BACK_BREADCRUMB'
export const SWITCH_HEADER_SEARCH_PERFORMED = 'SWITCH_HEADER_SEARCH_PERFORMED'
export const SWITCH_IS_FIRST_PAGE_VISITED = 'SWITCH_IS_FIRST_PAGE_VISITED'
// export const REDIRECT = 'REDIRECT'

export const SHOW_ALL = 'SHOW_ALL'

export const REQUEST_TUNES = 'REQUEST_TUNES'
export const RECEIVE_TUNES = 'RECEIVE_TUNES'